export type VerbKind = "read" | "session" | "write" | "send";

export interface DiscoveryStep {
  ui: string;
  click: string;
  sandboxHint: string;
  expectedPaths: string[];
  notes?: string;
}

export interface VerbSpec {
  verb: string;
  tool: string;
  httpPath: string;
  httpMethod: "GET" | "POST";
  kind: VerbKind;
  captured: boolean;
  description: string;
  sandboxRequired?: boolean;
  discovery?: DiscoveryStep;
}

export const VERBS: VerbSpec[] = [
  {
    verb: "session.status",
    tool: "bt_session_status",
    httpPath: "/v1/session/status",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Session + builder context (init + GlobalInfo).",
  },
  {
    verb: "jobs.picker.list",
    tool: "bt_jobs_picker_list",
    httpPath: "/v1/jobs/picker/list",
    httpMethod: "POST",
    kind: "read",
    captured: true,
    description: "Job picker rows.",
  },
  {
    verb: "jobs.picker.select",
    tool: "bt_jobs_picker_select",
    httpPath: "/v1/jobs/picker/select",
    httpMethod: "POST",
    kind: "session",
    captured: true,
    description: "Set the session job scope. Required before most job-scoped grids.",
  },
  {
    verb: "jobs.picker.existing",
    tool: "bt_jobs_picker_existing",
    httpPath: "/v1/jobs/picker/existing",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Existing job list for the signed-in user.",
  },
  {
    verb: "jobs.list",
    tool: "bt_jobs_list",
    httpPath: "/v1/jobs/list",
    httpMethod: "POST",
    kind: "read",
    captured: true,
    description: "Jobsites grid (filters id 33).",
  },
  {
    verb: "jobs.get",
    tool: "bt_jobs_get",
    httpPath: "/v1/jobs/get",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Single jobsite.",
  },
  {
    verb: "jobs.accountingLink",
    tool: "bt_jobs_accounting_link",
    httpPath: "/v1/jobs/accounting-link",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Accounting linked-entity info for a job.",
  },
  {
    verb: "jobs.create",
    tool: "bt_jobs_create",
    httpPath: "/v1/jobs/create",
    httpMethod: "POST",
    kind: "write",
    captured: false,
    sandboxRequired: true,
    description: "Create a jobsite. Path not fired — do not guess.",
    discovery: {
      ui: "/app/JobPage/0/1?openCondensed=true",
      click: "Fill a clearly fake sandbox job, Save. JS backlog mentions /api/jobsites/Add and /api/jobsites/DefaultInfo.",
      sandboxHint: "Sandbox job the operator names. Never a live client job.",
      expectedPaths: ["/api/jobsites/Add", "/api/jobsites/DefaultInfo"],
    },
  },
  {
    verb: "jobs.update",
    tool: "bt_jobs_update",
    httpPath: "/v1/jobs/update",
    httpMethod: "POST",
    kind: "write",
    captured: false,
    sandboxRequired: true,
    description: "Update job info. Save was not clicked — do not guess the PUT body.",
    discovery: {
      ui: "/app/JobPage/{jobId}/1",
      click: "Change a dummy field on a sandbox job, Save, then revert.",
      sandboxHint: "Sandbox job the operator names.",
      expectedPaths: ["/api/jobsites/"],
    },
  },
  {
    verb: "leads.list",
    tool: "bt_leads_list",
    httpPath: "/v1/leads/list",
    httpMethod: "POST",
    kind: "read",
    captured: true,
    description: "Lead Opportunities grid.",
  },
  {
    verb: "leads.get",
    tool: "bt_leads_get",
    httpPath: "/v1/leads/get",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Single lead.",
  },
  {
    verb: "leads.defaults",
    tool: "bt_leads_defaults",
    httpPath: "/v1/leads/defaults",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Lead create-form defaults.",
  },
  {
    verb: "leads.create",
    tool: "bt_leads_create",
    httpPath: "/v1/leads/create",
    httpMethod: "POST",
    kind: "write",
    captured: false,
    sandboxRequired: true,
    description: "Create a lead. Must capture. Do not submit leftover /Lead/0 tabs.",
    discovery: {
      ui: "/app/leads (Lead Opportunities add form from Defaults)",
      click: "Fill Defaults, save a clearly fake sandbox lead. Do not submit leftover /Lead/0 tabs.",
      sandboxHint: "Fake lead the operator approves.",
      expectedPaths: ["/api/Leads", "/api/Leads/{id}"],
    },
  },
  {
    verb: "leads.update",
    tool: "bt_leads_update",
    httpPath: "/v1/leads/update",
    httpMethod: "POST",
    kind: "write",
    captured: false,
    sandboxRequired: true,
    description: "Update a lead. Must capture.",
    discovery: {
      ui: "/app/leads/{id}",
      click: "Edit one field on a sandbox lead, Save, revert.",
      sandboxHint: "Fake lead the operator approves.",
      expectedPaths: ["/api/Leads", "/api/Leads/{id}"],
    },
  },
  {
    verb: "leads.convertToJob",
    tool: "bt_leads_convert_to_job",
    httpPath: "/v1/leads/convert-to-job",
    httpMethod: "POST",
    kind: "send",
    captured: false,
    sandboxRequired: true,
    description: "Creates a real job. Forbidden until send is enabled and create is captured.",
    discovery: {
      ui: "Lead detail — Convert to Job (canConvertToJob on GET)",
      click: "Do not click until this named send tool is enabled.",
      sandboxHint: "Creates a real job — send-locked.",
      expectedPaths: ["/api/Leads/", "convert"],
    },
  },
  {
    verb: "contacts.list",
    tool: "bt_contacts_list",
    httpPath: "/v1/contacts/list",
    httpMethod: "POST",
    kind: "read",
    captured: true,
    description: "Contacts grid.",
  },
  {
    verb: "contacts.get",
    tool: "bt_contacts_get",
    httpPath: "/v1/contacts/get",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Contact details. id 0 is the add form.",
  },
  {
    verb: "contacts.create",
    tool: "bt_contacts_create",
    httpPath: "/v1/contacts/create",
    httpMethod: "POST",
    kind: "write",
    captured: false,
    sandboxRequired: true,
    description: "Create a contact. Capture the POST before implementing.",
    discovery: {
      ui: "Contacts add form (GET /api/Contacts/0/Details)",
      click: "Add one sandbox contact, Save.",
      sandboxHint: "Fake contact the operator approves. Do not invent the POST.",
      expectedPaths: ["/api/Contacts"],
    },
  },
  {
    verb: "contacts.update",
    tool: "bt_contacts_update",
    httpPath: "/v1/contacts/update",
    httpMethod: "POST",
    kind: "write",
    captured: false,
    sandboxRequired: true,
    description: "Update a contact. Must capture.",
    discovery: {
      ui: "Contact details",
      click: "Edit one field, Save, revert.",
      sandboxHint: "Sandbox contact.",
      expectedPaths: ["/api/Contacts/{id}"],
    },
  },
  {
    verb: "invoices.list",
    tool: "bt_invoices_list",
    httpPath: "/v1/invoices/list",
    httpMethod: "POST",
    kind: "read",
    captured: true,
    description: "Owner invoices grid (filters id 39).",
  },
  {
    verb: "invoices.get",
    tool: "bt_invoices_get",
    httpPath: "/v1/invoices/get",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Owner invoice (progress claim).",
  },
  {
    verb: "invoices.accountingStatus",
    tool: "bt_invoices_accounting_status",
    httpPath: "/v1/invoices/accounting-status",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Accounting status for an owner invoice (entityType=3).",
  },
  {
    verb: "invoices.changes",
    tool: "bt_invoices_changes",
    httpPath: "/v1/invoices/changes",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Entity change tracking.",
  },
  {
    verb: "invoices.saveDraft",
    tool: "bt_invoices_save_draft",
    httpPath: "/v1/invoices/save-draft",
    httpMethod: "POST",
    kind: "write",
    captured: true,
    description: "Save owner-invoice draft via PUT /apix/v3/Invoices/save-invoice (merge-patch). Forces notifyOwner/createInvoiceChkbox false and status Draft. Never Send.",
  },
  {
    verb: "invoices.addLines",
    tool: "bt_invoices_add_lines",
    httpPath: "/v1/invoices/add-lines",
    httpMethod: "POST",
    kind: "write",
    captured: true,
    description: "Add owner-invoice lines via the same PUT /apix/v3/Invoices/save-invoice (merge-patch) with lineItems/ownerInvoiceLineItems. Add-from related picker GET is /api/LineItems/EntityLineItemsToInvoice. Never Send.",
  },
  {
    verb: "invoices.send",
    tool: "bt_invoices_send",
    httpPath: "/v1/invoices/send",
    httpMethod: "POST",
    kind: "send",
    captured: false,
    description: "Email/send an owner invoice. Forbidden default.",
    discovery: {
      ui: "Owner invoice — Send",
      click: "Do not click. Separate send-locked tool.",
      sandboxHint: "Never on a live owner invoice.",
      expectedPaths: [],
    },
  },
  {
    verb: "variations.list",
    tool: "bt_variations_list",
    httpPath: "/v1/variations/list",
    httpMethod: "POST",
    kind: "read",
    captured: true,
    description: "Change orders grid.",
  },
  {
    verb: "variations.get",
    tool: "bt_variations_get",
    httpPath: "/v1/variations/get",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Change order detail.",
  },
  {
    verb: "variations.saveDraftHeader",
    tool: "bt_variations_save_draft_header",
    httpPath: "/v1/variations/save-draft-header",
    httpMethod: "POST",
    kind: "write",
    captured: true,
    description: "PUT header only. Keeps approvalStatus 0 (Draft).",
  },
  {
    verb: "variations.saveDraft",
    tool: "bt_variations_save_draft",
    httpPath: "/v1/variations/save-draft",
    httpMethod: "POST",
    kind: "write",
    captured: true,
    description: "Alias of variations.saveDraftHeader.",
  },
  {
    verb: "variations.updateLine",
    tool: "bt_variations_update_line",
    httpPath: "/v1/variations/update-line",
    httpMethod: "POST",
    kind: "write",
    captured: true,
    description: "merge-patch+json line update.",
  },
  {
    verb: "variations.addLines",
    tool: "bt_variations_add_lines",
    httpPath: "/v1/variations/add-lines",
    httpMethod: "POST",
    kind: "write",
    captured: true,
    description: "application/json line add. Do not send forbidden GST fields.",
  },
  {
    verb: "variations.deleteLines",
    tool: "bt_variations_delete_lines",
    httpPath: "/v1/variations/delete-lines",
    httpMethod: "POST",
    kind: "write",
    captured: true,
    description: "Delete change-order line items.",
  },
  {
    verb: "variations.recomputeGst",
    tool: "bt_variations_recompute_gst",
    httpPath: "/v1/variations/recompute-gst",
    httpMethod: "POST",
    kind: "write",
    captured: true,
    description: "Recompute the 4000 GST dummy line from owner price (1/11 inclusive).",
  },
  {
    verb: "variations.createDraft",
    tool: "bt_variations_create_draft",
    httpPath: "/v1/variations/create-draft",
    httpMethod: "POST",
    kind: "write",
    captured: false,
    description: "New change order. JS-known, not fired.",
    discovery: {
      ui: "Change Orders — add new on a sandbox job",
      click: "Open new CO so Defaults + create-draft fire. Leave Draft.",
      sandboxHint: "Sandbox change-order draft.",
      expectedPaths: [
        "/api/ChangeOrders/Defaults",
        "/apix/v2/ChangeOrders/{id}/create-draft",
      ],
    },
  },
  {
    verb: "variations.notifyOwners",
    tool: "bt_variations_notify_owners",
    httpPath: "/v1/variations/notify-owners",
    httpMethod: "POST",
    kind: "send",
    captured: false,
    description: "Notify owners. Forbidden default.",
    discovery: {
      ui: "Change order — notify owners",
      click: "Do not click.",
      sandboxHint: "Never.",
      expectedPaths: ["notify-owners"],
    },
  },
  {
    verb: "bills.list",
    tool: "bt_bills_list",
    httpPath: "/v1/bills/list",
    httpMethod: "POST",
    kind: "read",
    captured: true,
    description: "Project AP bills grid.",
  },
  {
    verb: "bills.tabCounts",
    tool: "bt_bills_tab_counts",
    httpPath: "/v1/bills/tab-counts",
    httpMethod: "POST",
    kind: "read",
    captured: true,
    description: "Bill tab counts.",
  },
  {
    verb: "bills.get",
    tool: "bt_bills_get",
    httpPath: "/v1/bills/get",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Single bill.",
  },
  {
    verb: "bills.file",
    tool: "bt_bills_file",
    httpPath: "/v1/bills/file",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Bill file / preview.",
  },
  {
    verb: "bills.defaults",
    tool: "bt_bills_defaults",
    httpPath: "/v1/bills/defaults",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description:
      "Bill create seed (GET /api/v1/bills/defaultinfo). Cost codes, customFields, lienWaiverFormId — copy at runtime, never hard-code.",
  },
  {
    verb: "bills.availablePurchaseOrders",
    tool: "bt_bills_available_purchase_orders",
    httpPath: "/v1/bills/available-purchase-orders",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description:
      "Open POs for a vendor on a job. Captured read. A real PO link still needs GetBillMapping (not captured).",
  },
  {
    verb: "bills.create",
    tool: "bt_bills_create",
    httpPath: "/v1/bills/create",
    httpMethod: "POST",
    kind: "write",
    captured: true,
    sandboxRequired: true,
    description:
      "Create a project-expense bill as Draft (status 9): GET defaultinfo → POST /api/v1/bills → PUT save-draft with exclusive amounts. Optional PDF attach. Never pay / RFP / accounting.",
  },
  {
    verb: "bills.update",
    tool: "bt_bills_update",
    httpPath: "/v1/bills/update",
    httpMethod: "POST",
    kind: "write",
    captured: true,
    description:
      "Save draft (PUT /api/v1/bills/{id}, saveAsDraft true, status 9). Exclusive amounts only. Never Ready-for-Payment.",
  },
  {
    verb: "bills.attach",
    tool: "bt_bills_attach",
    httpPath: "/v1/bills/attach",
    httpMethod: "POST",
    kind: "write",
    captured: true,
    description:
      "Attach one PDF to a bill: tempFile (multipart) then EntityDocs documentType 58. Not ocr-upload. Not on bill POST/PUT.",
  },
  {
    verb: "bills.linkPurchaseOrder",
    tool: "bt_bills_link_purchase_order",
    httpPath: "/v1/bills/link-purchase-order",
    httpMethod: "POST",
    kind: "write",
    captured: false,
    description:
      "Link a real PO onto a bill. GetBillMapping was not captured — purchaseOrderId stays -1 (none).",
    discovery: {
      ui: "Bill — Purchase Order dropdown",
      click:
        "Select a real PO (not -- None Selected --) on a sandbox bill so GetBillMapping fires. Leave Draft. Do not mark ready for payment.",
      sandboxHint: "Project expense only. Do not guess isCreateNewFromPO: true.",
      expectedPaths: ["/api/v1/Bills/GetBillMapping"],
      notes:
        "GET get-available-purchase-orders is captured. Linking is not. purchaseOrderId: -1 means none.",
    },
  },
  {
    verb: "bills.markReadyForPayment",
    tool: "bt_bills_mark_ready_for_payment",
    httpPath: "/v1/bills/mark-ready-for-payment",
    httpMethod: "POST",
    kind: "send",
    captured: false,
    description:
      "Separate UI control (#markReadyForPaymentFromDraftButtonId). Do not call. Pay from your accounting system.",
    discovery: {
      ui: "Bill — Mark ready for payment",
      click: "Do not click. Pay from the accounting system, not Buildertrend.",
      sandboxHint: "Never.",
      expectedPaths: [],
    },
  },
  {
    verb: "pos.list",
    tool: "bt_pos_list",
    httpPath: "/v1/pos/list",
    httpMethod: "POST",
    kind: "read",
    captured: true,
    description: "Purchase orders grid.",
  },
  {
    verb: "pos.get",
    tool: "bt_pos_get",
    httpPath: "/v1/pos/get",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Single purchase order.",
  },
  {
    verb: "pos.linkedBills",
    tool: "bt_pos_linked_bills",
    httpPath: "/v1/pos/linked-bills",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Bills linked on a PO (from PO get payload).",
  },
  {
    verb: "pos.linkedBids",
    tool: "bt_pos_linked_bids",
    httpPath: "/v1/pos/linked-bids",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Bids linked on a PO (from PO get payload).",
  },
  {
    verb: "pos.approvals",
    tool: "bt_pos_approvals",
    httpPath: "/v1/pos/approvals",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "PO approvals (from PO get payload). Do not auto-approve.",
  },
  {
    verb: "pos.create",
    tool: "bt_pos_create",
    httpPath: "/v1/pos/create",
    httpMethod: "POST",
    kind: "write",
    captured: false,
    description: "Create a PO. Capture then implement. Do not auto-approve.",
    discovery: {
      ui: "Purchase Orders — add on a sandbox job",
      click: "Create a draft PO for a project expense, Save. Do not approve.",
      sandboxHint: "Project expenses only.",
      expectedPaths: ["/api/PurchaseOrders"],
    },
  },
  {
    verb: "pos.update",
    tool: "bt_pos_update",
    httpPath: "/v1/pos/update",
    httpMethod: "POST",
    kind: "write",
    captured: false,
    description: "Update a PO. Do not auto-approve.",
    discovery: {
      ui: "Purchase order detail",
      click: "Edit a restoreable field, Save, revert.",
      sandboxHint: "Sandbox PO.",
      expectedPaths: ["/api/PurchaseOrders/{id}"],
    },
  },
  {
    verb: "estimates.worksheet",
    tool: "bt_estimates_worksheet",
    httpPath: "/v1/estimates/worksheet",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Estimate worksheet. Respect worksheetLocked.",
  },
  {
    verb: "estimates.updateLine",
    tool: "bt_estimates_update_line",
    httpPath: "/v1/estimates/update-line",
    httpMethod: "POST",
    kind: "write",
    captured: false,
    description: "JS-known, not fired. Do not send to budget.",
    discovery: {
      ui: "Estimate worksheet on a sandbox job that is not locked",
      click: "Edit one line, Save. Confirm worksheetLocked is false. Do not send to budget.",
      sandboxHint: "Unlocked estimating sandbox.",
      expectedPaths: ["/apix/v2/LineItems/update-estimate-line-item"],
    },
  },
  {
    verb: "estimates.addLines",
    tool: "bt_estimates_add_lines",
    httpPath: "/v1/estimates/add-lines",
    httpMethod: "POST",
    kind: "write",
    captured: false,
    description: "JS-known, not fired.",
    discovery: {
      ui: "Estimate worksheet",
      click: "Add one line, Save. Do not send to budget.",
      sandboxHint: "Unlocked worksheet.",
      expectedPaths: ["/apix/v2/LineItems/add-estimate-line-items"],
    },
  },
  {
    verb: "estimates.sendToBudget",
    tool: "bt_estimates_send_to_budget",
    httpPath: "/v1/estimates/send-to-budget",
    httpMethod: "POST",
    kind: "send",
    captured: false,
    description: "isSentToBudget. Named tool, default off.",
    discovery: {
      ui: "Estimate — send to budget",
      click: "Do not click unless this named send tool is enabled.",
      sandboxHint: "Budget lock can hurt jobs.",
      expectedPaths: [],
    },
  },
  {
    verb: "docs.root",
    tool: "bt_docs_root",
    httpPath: "/v1/docs/root",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Job documents root (mediaType=1).",
  },
  {
    verb: "docs.folder",
    tool: "bt_docs_folder",
    httpPath: "/v1/docs/folder",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Folder contents.",
  },
  {
    verb: "docs.file",
    tool: "bt_docs_file",
    httpPath: "/v1/docs/file",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "File metadata / preview / download.",
  },
  {
    verb: "docs.upload",
    tool: "bt_docs_upload",
    httpPath: "/v1/docs/upload",
    httpMethod: "POST",
    kind: "write",
    captured: false,
    description:
      "Upload / add folder on job documents. Not captured. Bill PDF attach is bills.attach (captured).",
    discovery: {
      ui: "Job documents — sandbox folder",
      click: "Upload a tiny test file, then implement from the capture.",
      sandboxHint: "Sandbox folder only.",
      expectedPaths: ["/api/files", "/api/MediaFolders"],
    },
  },
  {
    verb: "costing.header",
    tool: "bt_costing_header",
    httpPath: "/v1/costing/header",
    httpMethod: "POST",
    kind: "read",
    captured: true,
    description: "Job costing budget header.",
  },
  {
    verb: "costing.views",
    tool: "bt_costing_views",
    httpPath: "/v1/costing/views",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Job costing views.",
  },
  {
    verb: "costing.lines",
    tool: "bt_costing_lines",
    httpPath: "/v1/costing/lines",
    httpMethod: "POST",
    kind: "read",
    captured: true,
    description: "Job costing line items. Writes out of scope (budget lock).",
  },
  {
    verb: "costing.searchCostCodes",
    tool: "bt_costing_search_cost_codes",
    httpPath: "/v1/costing/search-cost-codes",
    httpMethod: "POST",
    kind: "read",
    captured: true,
    description: "Cost-code search (categories:[30]).",
  },
  {
    verb: "sync.pull",
    tool: "bt_sync_pull",
    httpPath: "/v1/sync/pull",
    httpMethod: "POST",
    kind: "read",
    captured: true,
    description: "Pull used modules into mirror tables + sync_state.",
  },
  {
    verb: "sync.status",
    tool: "bt_sync_status",
    httpPath: "/v1/sync/status",
    httpMethod: "GET",
    kind: "read",
    captured: true,
    description: "Mirror / command-log status.",
  },
];

export const VERB_BY_NAME = new Map(VERBS.map((v) => [v.verb, v]));
export const VERB_BY_TOOL = new Map(VERBS.map((v) => [v.tool, v]));
export const VERB_BY_HTTP = new Map(VERBS.map((v) => [v.httpPath, v]));

export function remainingCaptures(): VerbSpec[] {
  return VERBS.filter((v) => !v.captured && v.kind !== "send");
}

export function sendVerbs(): VerbSpec[] {
  return VERBS.filter((v) => v.kind === "send");
}
